spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 280406843015-laqh2p84ms8fdc73iooo912a247a1m6g.apps.googleusercontent.com
            client-secret: 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