spring:
  application:
    name: libraryapi
  output:
    ansi:
      enAbled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
  life:
    name: app.log
  level:
    root: warn
    io:
      github:
        fabiofavaleiro: trace
#          conbtroller: error
        web: debug
        security: trace
#    orb:
#      springframework:
#        web: debug

#Leveis de hierarquia o de cima incloba todos os de baixo:

# trace
# debug
# info
# warn
# error

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  override-with-generic-response: false